# Generated by Django 5.1.1 on 2025-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='m6Kesl5IdYyri4DQYvmviojcQUUHZVkJ', editable=False, max_length=32, unique=True),
        ),
    ]
