# Generated by Django 5.1.1 on 2025-05-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_customuser_is_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='DH8NL4EDFrDf3d7QX8tQ4YDsRiq43Ixv', editable=False, max_length=32, unique=True),
        ),
    ]
