# Generated by Django 5.1.1 on 2025-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='BOCZNIzMu5QeWxIcctrcUFSWHwTkWX3L', editable=False, max_length=32, unique=True),
        ),
    ]
